vim.g.neovide_animation_lenght = 0.3
vim.g.neovide_confirm_quit = true
vim.g.neovide_cursor_animate_command_line = true
vim.g.neovide_cursor_animation_length = 0.075
vim.g.neovide_cursor_antialiasing = true
vim.g.neovide_cursor_trail_size = 0.8
vim.g.neovide_cursor_unfocused_outline_width = 0.05
vim.g.neovide_cursor_vfx_mode = "ripple"
vim.g.neovide_floating_blur_amount_x = 8.0
vim.g.neovide_floating_blur_amount_y = 8.0
vim.g.neovide_fullscreen = false
vim.g.neovide_hide_mouse_when_typing = true
vim.g.neovide_no_idle = false
vim.g.neovide_padding_bottom = 0
vim.g.neovide_padding_left = 0
vim.g.neovide_padding_right = 0
vim.g.neovide_padding_top = 0
vim.g.neovide_profiler = false
vim.g.neovide_refresh_rate = 165
vim.g.neovide_refresh_rate_idle = 5
vim.g.neovide_transparency = 0.75
vim.g.neovide_underline_automatic_scaling = true
vim.o.guifont = "FiraCode Nerd Font Mono:h12:#e-subpixelantialias"
vim.opt.linespace = 1

